name: build and deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: build and deploy gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: use node.js@14.12.x
        uses: actions/setup-node@main
        with:
          node-version: 14.12.x

      - name: create config.json
        run: |
          echo '{ "api_origin": "${{secrets.API_ORIGIN}}", "pwa_origin": "${{secrets.PWA_ORIGIN}}", "github_repository": "https://github.com/mebtte/cicada_pwa" }' > config.json

      - name: build
        run: |
          npm install
          npm run build

      # - name: styleguide build
      #   run: |
      #     npm run styleguide:build

      - name: create cname file
        run: |
          echo ${{secrets.PWA_ORIGIN}} > build/CNAME

      - name: deploy gh-pages
        run: |
          cd build
          git init
          git config --local user.name mebtte
          git config --local user.email hi@mebtte.com
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy gh-pages"
          git push origin gh-pages -f
